"use strict";

Object.size = function(obj) {
    var size = 0, key;
    for (key in obj) {
        if (obj.hasOwnProperty(key)) {
            size++;
        }
    }
    return size;
};

function Writer() {
    /**
     * Takes an object generated by Reader.read and returns
     * a HTML string. wraps the html into a div.
     */
    Writer.prototype.write = function(markdownObject) {
        var html = "";
        //var element = markdownObject[slideNumber][position];

        var slideCounter = 1;
        for (var key in markdownObject) {
            var slide = markdownObject[key];
            html += "<div class='slide' id='slide" + slideCounter + "'>\n";

            for (var k in slide) {
                var element = slide[k];
                if (element.style === "header1") {
                    html += this.writeHeader1(element) + "\n";

                } else if (element.style === "header2") {
                    html += this.writeHeader2(element) + "\n";

                } else if (element.style === "header3") {
                    html += this.writeHeader3(element) + "\n";

                } else if (element.style === "normaltext") {
                    html += this.writeNormalText(element) + "\n";

                } else if (element.style === "bigtext") {
                    html += this.writeBigText(element) + "\n";

                } else if (element.style === "image") {
                    html += this.writeImage(element) + "\n";

                } else {
                    html += this.writeNormalText(element) + "\n";
                }
            }
            html += "</div>\n\n";
            slideCounter++;
        }
        return html;
    };

    Writer.prototype.writeNormalText = function(element) {
        return "<p>" + element.text + "</p>";
    };

    Writer.prototype.writeBigText = function(element) {
        return "<p class='bigtext'>" + element.text + "</p>";
    };

    Writer.prototype.writeImage = function(element) {
        return "<img src='" + element.text + "' />";
    };

    Writer.prototype.writeHeader1 = function(element) {
        return "<h1>" + element.text + "</h1>";
    };

    Writer.prototype.writeHeader2 = function(element) {
        return "<h2>" + element.text + "</h2>";
    };

    Writer.prototype.writeHeader3 = function(element) {
        return "<h3>" + element.text + "</h3>";
    };

    /**
     * Takes an object generated by Reader.read and
     * generates an unordered list using titles and
     * slidenumbers. returns a HTML string. wraps
     * the html into a div.
     */
    Writer.prototype.writeTableOfContent = function(markdownObject) {
        var html = "";

        html += "<div id='content'>\n";
        html += "<ul>\n";

        var slideCounter = 1;
        for (var key in markdownObject) {
            var slide = markdownObject[key];

            for (var k in slide) {
                var element = slide[k];
                if (element.style === "header1" || element.style === "header2" || element.style === "header3") {  // only titles
                    html += "<li><a href='#slide" + slideCounter + "'>" + element.text + " " + slideCounter + "</a></li>\n";
                }
            }
            slideCounter++;
        }

        html += "</ul>\n";
        html += "</div>\n\n";

        return html;
    };
}
